spring:
  application:
    name: StudentManagementSystem
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /api
  port: 8083
app:
  jwt:
    secret: ${secretkey}
    expiration-ms: 86400000